[package]
name = "jeb1pochybrid"
version = "0.1.0"
edition = "2024"
description = ""
license = "MIT"
authors = ["Jebbex <107323805+Jebbex1@users.noreply.github.com>"]
readme = "../README.md"

[lib]
name = "jeb1pochybrid"
path = "src/lib.rs"

[dependencies]
